trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      # Filtra directamente por el Tag de Cucumber que ya tiene tu escenario
      tasks: 'clean test -Dcucumber.filter.tags="@SuccessfulLogin"'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      jdkArchitectureOption: 'x64'
    env:
      GRADLE_OPTS: '-Xmx3072m -XX:MaxMetaspaceSize=512m'


  - task: PublishHtmlReport@1
    displayName: 'Publicar Reporte de Serenity BDD'
    inputs:
      reportDir: 'target/site/serenity'
      tabName: 'Serenity Report'
    condition: always() # Esto asegura que el reporte se publique así la prueba falle o pase