trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'clean test --tests "com.bonbonite.runners.LoginUserRunner"'  # se ajustó para que solo corra login.feature
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'  # ¡Actualizado a Java 21 para hacer match con tu proyecto!
      jdkArchitectureOption: 'x64'
    env:
      # Asignación correcta de memoria para evitar fallos de Heap en el agente Linux
      GRADLE_OPTS: '-Xmx3072m -XX:MaxMetaspaceSize=512m'